datasources:
  default:
    connection:
      url: ${MONGO_URL}
    objectFiles:
      - "./src/**"
    appFiles:
      - "./src/**"
public:
  webservices:
    www:
      status: active
      url: 'https://www.steedos.com:443'
    creator:
      status: active
      url: ${ENV_CREATOR_URL}
    workflow:
      status: active
      url: ${ENV_WORKFLOW_URL}
  cfs:
    store: ${ENV_CFS_STORE}
    local:
      folder: ${ENV_STORAGE_DIR}
  admin:
    disableAddSpace: false
  accounts:
    disableAccountRegistration: false
    UTF8_Names_Validation: '[A-Za-z0-9-_.\u00C0-\u017F\u4e00-\u9fa5]+'
    loginExpirationInDays: 1825
  phone:
    forceAccountBindPhone: false
  cloudAdminSpaceId: cloud_admin
  templateSpaceId: 5e38d51b41386900110ff5c5
  is_group_company: true
cfs:
  aliyun:
    region: ${ENV_CFS_ALIYUN_REGION}
    bucket: ${ENV_CFS_ALIYUN_BUCKET}
    accessKeyId: ${ENV_CFS_ALIYUN_ACCESSKEYID}
    secretAccessKey: ${ENV_CFS_ALIYUN_SECRETACCESSKEY}
  worker:
    enabled: true
email:
  from: 华炎云 <noreply@steedos.com>
  url: xxx
logger:
  enabled: true
  showPackage: true
  showFileAndLine: true
  logLevel: 0
  viewLimit: 1000
billing:
  appid: ${ENV_BILLING_APPID}
  mch_id: ${ENV_BILLING_MCH_ID}
  partner_key: ${ENV_BILLING_PARTNER_KEY}
qiyeweixin:
  '-sync_interval': 600000
  authorize_uri: 'https://open.weixin.qq.com/connect/oauth2/authorize'
  api:
    getLoginInfo: 'https://qyapi.weixin.qq.com/cgi-bin/service/get_login_info'
    getProviderToken: 'https://qyapi.weixin.qq.com/cgi-bin/service/get_provider_token'
    getSuiteAccessToken: 'https://qyapi.weixin.qq.com/cgi-bin/service/get_suite_token'
    getPreAuthCode: 'https://qyapi.weixin.qq.com/cgi-bin/service/get_pre_auth_code'
    getPermanentCode: 'https://qyapi.weixin.qq.com/cgi-bin/service/get_permanent_code'
    getCorpToken: 'https://qyapi.weixin.qq.com/cgi-bin/service/get_corp_token'
    getDepartmentList: 'https://qyapi.weixin.qq.com/cgi-bin/department/list'
    getUserList: 'https://qyapi.weixin.qq.com/cgi-bin/user/list'
    getAllUserList: 'https://qyapi.weixin.qq.com/cgi-bin/user/list'
    getAdminList: 'https://qyapi.weixin.qq.com/cgi-bin/service/get_admin_list'
    getUserInfo3rd: 'https://qyapi.weixin.qq.com/cgi-bin/service/getuserinfo3rd'
plugins:
  - "@steedos/accounts"
tenant:
  saas: true
  enable_password_login: true
  name: 华炎云
  enable_mobile_code_login: true
  enable_register: true
  disable_email_register: true
  enable_bind_mobile: true
webservices:
  steedos: ${ENV_CREATOR_URL}
accounts:
  mobile_phone_locales: ['zh-CN']